channels:
  - conda-forge
dependencies:
  - astropy
  - dust_extinction
  - dsps==0.3.5
  - diffstar==0.2.2
  - diffmah==0.4.2
  - h5py
  - galsim
  - jax==0.4.19
  - lsstdesc-diffsky==1.0.0
  - matplotlib
  - metadetect
  - ngmix
  - numpy
  - pyarrow
  - python<3.12
  - scipy<1.13.0
  - yaml
