name: chromatic-shear-bias
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - dust_extinction
  - fitsio
  - galsim
  - galsim_extra
  - joblib
  - lsstdesc_diffsky==v1.0.0
  - dsps==v0.3.5
  - diffstar==v0.2.2
  - matplotlib
  - metadetect
  - ngmix
  - numpy
  - psutil
  - pyarrow
  - tqdm
  - yaml
