name: chromatic-shear-bias
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - dust_extinction
  - fitsio
  - galsim
  - galsim_extra
  - joblib
  - lsstdesc_diffsky
  - dsps
  - diffstar
  - matplotlib
  - metadetect
  - ngmix
  - numpy
  - psutil
  - pyarrow
  - tqdm
  - yaml
